export const GET_CURRENT_COUNT_SUCCESS = 'GET_CURRENT_COUNT_SUCCESS';
export const GET_NEXT_COUNT_SUCCESS = 'GET_NEXT_COUNT_SUCCESS';
export const UPDATE_CURRENT_COUNT_SUCCESS = 'UPDATE_CURRENT_COUNT_SUCCESS';